### ISSUE TITLE
Sphinx 6.0+ causes deprecation warnings when running tests

### ISSUE THREAD

**Issue by jnikula** [jnikula/hawkmoth#114]
Running tests through the Sphinx application and extension, i.e. `test_cautodoc.py`, causes Sphinx deprecation warnings with Sphinx 6.0+. For example:

```
$ pytest -v -k test_cautodoc

[...]

test/test_cautodoc.py::test_directive_text[autoenum]
test/test_cautodoc.py::test_directive_text[autoenum]
  /usr/lib/python3.9/importlib/__init__.py:127: RemovedInSphinx80Warning: The alias 'sphinx.util.SkipProgressMessage' is deprecated, use 'sphinx.util.display.SkipProgressMessage' instead. Check CHANGES for Sphinx API modifications.
    return _bootstrap._gcd_import(name[level:], package, level)

test/test_cautodoc.py::test_directive_text[autoenum]
test/test_cautodoc.py::test_directive_text[autoenum]
test/test_cautodoc.py::test_directive_text[autoenum]
test/test_cautodoc.py::test_directive_text[autoenum]
  /usr/lib/python3.9/importlib/__init__.py:127: RemovedInSphinx80Warning: The alias 'sphinx.util.progress_message' is deprecated, use 'sphinx.util.display.progress_message' instead. Check CHANGES for Sphinx API modifications.
    return _bootstrap._gcd_import(name[level:], package, level)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================= 66 passed, 68 deselected, 2 xfailed, 8 warnings in 5.78s ========================
```

Where do these come from? Maybe `sphinx_testing` package?

**Comment by jnikula** [comment]
I'm clueless. Reported upstream: https://github.com/sphinx-doc/sphinx/issues/11138

**Comment by jnikula** [comment]
@BrunoMSantos Do you see the warnings?

**Comment by BrunoMSantos** [comment]
My system version of Sphinx is 5.3.0... No issues on that one. I'll probably face the same music in a few weeks time though.

> Where do these come from? Maybe sphinx_testing package?

My guess is yes, but I've honestly been waiting for the v6 update.

**Comment by jnikula** [comment]
I must have started converting `sphinx_testing` to `sphinx.testing` half a dozen times, and always given up. There's hardly any documentation, especially on transition, and there doesn't seem to be anything as convenient as `@with_app`.
