### ISSUE TITLE
Improve documentation generation on compiler failures due to incomplete types

### ISSUE THREAD

**Issue by jnikula** [jnikula/hawkmoth#13]
Is there no way to just print the symbol even though the compiler fails? It seems like a big pain to add all the include paths for external code just to compile the documentation.

It's also a bit strange that 1 linkage failure within a structure makes the structure anonymous rather than providing it's typedef'ed name.

_Originally posted by @Livingwind in https://github.com/jnikula/hawkmoth/issues/11#issuecomment-490608503_

**Comment by speedyleion** [comment]
I will say, I'm fond of the simplicity of the internals of [parser.py](https://github.com/jnikula/hawkmoth/blob/master/hawkmoth/parser.py), and any change based on this information would probably force special handling.

It is possible to key on the type definition more.

In this example the following `TYPEDEF_DECL` will have one child node which is the `STRUCT_DECL`.
```
/**
 * Unknown type
 */
typedef struct {
	/**
	 * Unknown type
	 */
	taco m;
} unknown_member_type
```

A typedef without a struct declaration has `TYPE_REF` node as it's child, `foo` in the example below
```
struct named {
	/**
	 * named member
	 */
	int m;
};

/**
 * A type without a struct declaration inside
 */
typedef struct named foo;
```

**Comment by jnikula** [comment]
> I will say, I'm fond of the simplicity of the internals of [parser.py](https://github.com/jnikula/hawkmoth/blob/master/hawkmoth/parser.py), and any change based on this information would probably force special handling.

Indeed simplicity is one of the selling points of Hawkmoth, and the number of lines to implement a feature will be a consideration. There'll always be Doxygen+Breathe when Hawkmoth is not enough, and I'm not even trying to compete with that combo.

**Comment by LudovicGuerra** [comment]
> 
> 
> > I will say, I'm fond of the simplicity of the internals of [parser.py](https://github.com/jnikula/hawkmoth/blob/master/hawkmoth/parser.py), and any change based on this information would probably force special handling.
> 
> Indeed simplicity is one of the selling points of Hawkmoth, and the number of lines to implement a feature will be a consideration. There'll always be Doxygen+Breathe when Hawkmoth is not enough, and I'm not even trying to compete with that combo.

After having test the combo, it is not useable at the moment due to the slowness. I have 6500 XML files generated on only one submodule, and breathe parser is so slow it takes 10 min to file one autodoc. There is room to "compete" even in simplicity ^^.
