### ISSUE TITLE
Add enumerator values in documentation

### ISSUE THREAD

**Issue by jnikula** [jnikula/hawkmoth#175]
The Sphinx C and C++ domain directive for enumerators allows optionally specifying the enumerator value:

```
.. c:enumerator:: name = value
```

It would be straightforward to unconditionally add it (the Cursor for `CursorKind.ENUM_CONSTANT_DECL` has `enum_value` property), but the question is whether that is the right thing to do.

The alternatives:

- Always display value
- Display value if the source code explicitly sets it. This is what Doxygen appears to do. I think this requires looking at the tokens. I've implemented this in #176 
- Make it configurable, could be done globally and at `c:autoenum::`
- Never display value (status quo)

I'm not really fond of adding a lot of configuration, and would prefer sane defaults instead.

@BrunoMSantos thoughts?

**Comment by BrunoMSantos** [comment]
I replied in #176, but to be explicit, I like the Doxygen behaviour here. I don't see much value in making it configurable personally and we can always add that later if anyone wants it I guess, keeping the Doxygen behaviour as default.
