### ISSUE TITLE
Need assistance to use Hawhmoth

### ISSUE THREAD

**Issue by LudovicGuerra** [jnikula/hawkmoth#18]
Hi.
I am using Hawkmoth, the setup is working.
But I have some difficulties for 2 points at the moment and couldn't solve it myself:
- I have an include `#include<sys/type.h>` but Hawkmoth give me a warning that he doesn't finds the file. I tried several location but still not working. Could you tell me from where Hawkmoth is searching the file ?
- I don't see anywhere any explanation of what -DHAWKMOTH is doing.

Thank you !

**Comment by jnikula** [comment]
`-DHAWKMOTH` is merely an example to show how you could pass that to clang, for example to enable conditional parsing for documentation.

You may need to pass your include path to clang via some `-I<PATH>` option to allow clang to find the relevant files.

**Comment by LudovicGuerra** [comment]
Thank you it worked like a charm. And good that we can specify a clang parameters for each autodoc !
