### ISSUE TITLE
Pass them cursors around

### ISSUE THREAD

**Issue by BrunoMSantos** [jnikula/hawkmoth#180]
This is a bit of a meta issue. It's meant as a place to discuss a grand refactor (or multiple smaller ones) which have been discussed between me and @jnikula several times for a long time without any single place to consolidate ideas.

The aim is to address issues like:
- Parser complexity, particularly with regards to docstring generation coupling.
- Expand extension API.

With no prejudice to other ideas, our best concept so far is to pass _a cursor_ object around a bit more instead of digesting it directly in `parser.py`. This would help in obvious ways:
- The docstring module could stop using the convoluted list of named parameters that take on different meanings depending on context and which need to be carefully constructed and passed by the main parser loop right now.
- Decoupling docstring generation would also improve legibility on the recursive bits of the parser which are currently a big limitation for better C++ support for instance.
- Extensions could have direct access to the cursor, unlocking a lot of nice possibilities with a simpler API. #92 and #179 come to mind, but I'm sure this has come up more times than those two.

As for implementation ideas, maybe the biggest question is: should we pass the clang cursor or an abstraction of our own?

Personally, I feel the clang cursor is way too low level. I'd like a documentation centric cursor type of our own to abstract the things we care about (e.g. no point in having a plugin repeat the weird logic to parse qualifiers that we already need internally) and also to decouple hawkmoth extensions from clang versions while at it. I'm not sure I've heard @jnikula's opinion on the matter though... Am I overcomplicating?

**Comment by jnikula** [comment]
Thanks for starting this.

I guess I've been pretty adamant so far that `docstring.py` shouldn't know anything about clang or cursors. There's a bunch of complexity in dealing with cursors, and I've thought it's better to keep all of that hidden in `parser.py`.

That in turn has meant that `parser.py` has to know a bunch of stuff about `Docstring` objects. I think the division has mostly worked all right, but doesn't mean other alternatives wouldn't work as well.

> The docstring module could stop using the convoluted list of named parameters that take on different meanings depending on context and which need to be carefully constructed and passed by the main parser loop right now.

Side note, I think this part could be improved quite a bit just by adding `__init__()` methods to all subclasses of `Docstring`, and only having the relevant parameters, maybe also dropping the default values to require them. I think that should be done regardless of passing cursor around more (and in fact I have draft patches for this in some branch).

---

I agree clang cursor feels too low level to pass around to extensions. However, abstracting it for the purpose of making it easier or more convenient for extensions might a) reduce the usefulness of passing the cursor or its abstraction around in the first place, b) require complex code in Hawkmoth which I try to avoid, and c) lead to incrementally growing the abstraction to be able to do stuff in the extensions.

Sphinx autodoc passes the Python object to the events, and even specifically says the extensions can modify the objects in place: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#docstring-preprocessing. That feels pretty low level to me.

I guess I'm leaning towards passing the cursors, and perhaps providing helpers for dealing with them. It could lead to complexity in the extensions, but also makes them really powerful, and avoids complexity in Hawkmoth.

**Comment by jnikula** [comment]
> Extensions could have direct access to the cursor, unlocking a lot of nice possibilities with a simpler API. #92 and #179 come to mind, but I'm sure this has come up more times than those two.

Unfortunately, #92 is surprisingly complex. I thought it would be just "if there's `_Bool`, see if the code originally had `bool`, and if yes, convert." Specifically, figuring out the macro expansion doesn't work as easily as you'd think. See e.g. https://stackoverflow.com/questions/16786767/obtain-original-unexpanded-macro-text-using-libclang. But that's a bit bit off-topic here.

**Comment by BrunoMSantos** [comment]
> Thanks for starting this.
> 
> I guess I've been pretty adamant so far that `docstring.py` shouldn't know anything about clang or cursors. There's a bunch of complexity in dealing with cursors, and I've thought it's better to keep all of that hidden in `parser.py`.

Hmm, I specifically remember you suggesting the opposite. Not that it matters either way because I don't want it to know about clang's cursor either. Knowing of our own on the other hand... See below.

> That in turn has meant that `parser.py` has to know a bunch of stuff about `Docstring` objects. I think the division has mostly worked all right, but doesn't mean other alternatives wouldn't work as well.
> 
> > The docstring module could stop using the convoluted list of named parameters that take on different meanings depending on context and which need to be carefully constructed and passed by the main parser loop right now.
> 
> Side note, I think this part could be improved quite a bit just by adding `__init__()` methods to all subclasses of `Docstring`, and only having the relevant parameters, maybe also dropping the default values to require them. I think that should be done regardless of passing cursor around more (and in fact I have draft patches for this in some branch).

Maybe I'm misunderstanding your idea, but it's in the docstring context we know how we're formatting the output, so why not call the (e.g.) 'get a function return type' method there instead of the caller having to know in advance to provide it?

My suggestion is that our own cursor provides the methods to extract bits that are relevant for documentation in a documentation worthy format already. Docstring would _maybe_ have a more idiomatic API and implementation and probably be simpler in this case.

Note that doesn't work so well with the clang cursor, or at least we'd need to call helper functions to operate on it and so on... Like what you suggest for the extension API below. Not as neat I think.

> I agree clang cursor feels too low level to pass around to extensions. However, abstracting it for the purpose of making it easier or more convenient for extensions might a) reduce the usefulness of passing the cursor or its abstraction around in the first place,

Well, the user would depend on us exposing specific bits for sure, but I don't see this as a big issue. We'd simply provide methods in the cursor to get what we need. And power users _could_ access `our_cursor._private_clang_cursor`. Python doesn't really have private stuff anyway.

> b) require complex code in Hawkmoth which I try to avoid, and

Again don't see the issue. The code in this cursor would be the code we currently have in the parser.

> c) lead to incrementally growing the abstraction to be able to do stuff in the extensions.

I'll concede this one... Though I probably don't feel as strongly about it as you may.

> Sphinx autodoc passes the Python object to the events, and even specifically says the extensions can modify the objects in place: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#docstring-preprocessing. That feels pretty low level to me.

I think there's a world of difference there though. Python's objects already have documentation baked into them and introspection of their own. Clang's cursors are just convoluted C/C++ syntax.

> I guess I'm leaning towards passing the cursors, and perhaps providing helpers for dealing with them. It could lead to complexity in the extensions, but also makes them really powerful, and avoids complexity in Hawkmoth.

Right. Now if we wrap those helper functions and that cursor in a class, we get our custom 'cursor' (not even sure cursor is the right name). Same code, possibly more idiomatic, no?

**Comment by jnikula** [comment]
> Maybe I'm misunderstanding your idea, but it's in the docstring context we know how we're formatting the output, so why not call the (e.g.) 'get a function return type' method there instead of the caller having to know in advance to provide it?
> 
> My suggestion is that our own cursor provides the methods to extract bits that are relevant for documentation in a documentation worthy format already. Docstring would _maybe_ have a more idiomatic API and implementation and probably be simpler in this case.

Okay, that sounds interesting. How far do you think that should go? If what we have now is the one extreme, and the other extreme would be `parser.py` just creating abstracted cursor objects, passing them to some Docstring factory, and that would "ask" the cursor all the details that are now passed as constructor parameters?

**Comment by jnikula** [comment]
Also, would the cursor wrapper be a single class, or a hierarchy of classes that would somewhat map to Docstring classes?

**Comment by BrunoMSantos** [comment]
Hmm, not sure honestly... I did play around with this on and off and the concept I had in mind so far was the 'parser as a cursor builder' type with a shallow wrapper of clang's cursor. I'm not even seeing what that other alternative would look like, but it may be interesting.
