### ISSUE TITLE
ImportError: cannot import name Directive with Sphinx 1.8.2

### ISSUE THREAD

**Issue by onkwon** [jnikula/hawkmoth#2]
Here is the error message:

```
Traceback (most recent call last):
  File "cautodoc.py", line 20, in <module>
    from sphinx.util.compat import Directive
ImportError: cannot import name Directive
```

And I found [the issue](https://github.com/spinus/sphinxcontrib-images/issues/41) on the Sphinx Github issues list and removed

`from sphinx.util.compat import Directive`

line and replaced 

`from docutils.parsers.rst import directives`

with

`from docutils.parsers.rst import Directive, directives`

 in `cautodoc.py` fixed the problem.

**Comment by jnikula** [comment]
Thanks for your report! Fixed by commit 92617df84ce3 ("cautodoc: fix dependency on deprecated module").
