### ISSUE TITLE
Start making github releases

### ISSUE THREAD

**Issue by jnikula** [jnikula/hawkmoth#202]
BTW releases .. is it possible to start making github releases?🤔
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

_Originally posted by @kloczek in https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1773932796_

**Comment by jnikula** [comment]
At the high level, I'm not keen on becoming more dependent on github as a platform. To me, tagging and pushing is the release, and that would work in any forge.

That said, I'll look into a github workflow that will create the github notion of a release once I push an annotated tag.

**Comment by kloczek** [comment]
Creating gh rerelease entry do not generate any dependency.
It is yet another channel which could be used to spread notifications about new releases  .. only this and nothing more.
gh release entry is created on top of existing git tag.

**Comment by jnikula** [comment]
I've set up the github workflow to generate the releases. I've tried it on a sandbox repo, let's hope it works when I do the next release.

I'll probably manually create gh releases for older tags.

**Comment by kloczek** [comment]
Thank you very much 👍 😄

**Comment by jnikula** [comment]
> Thank you very much 👍 😄

Well, thank you for your help in making hawkmoth better! :clap:

**Comment by jnikula** [comment]
> I've set up the github workflow to generate the releases. I've tried it on a sandbox repo, let's hope it works when I do the next release.

Yay, seems to work. v0.17.0 is now available!
