### ISSUE TITLE
Make it possible to build hawkmoth documentation without the package installed

### ISSUE THREAD

**Issue by jnikula** [jnikula/hawkmoth#203]
https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1768442622_ by @kloczek

Would you accept PR with below patch?
```patch
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -5,6 +5,7 @@

 import os
 import sys
+sys.path.insert(0, os.path.abspath('../src'))

 # -- Project information -----------------------------------------------------
 # https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
```
It allows build documention out of only source tree without have `hawkmoth` installed.
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v7.1.2
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 9 added, 0 changed, 0 removed
reading sources... [100%] troubleshooting
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-hawkmoth.3 { installation extension directives syntax examples extending built-in-extensions troubleshooting } done
build succeeded.

The manual pages are in build/sphinx/man.
```
🤔

_Originally posted by @kloczek in https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1768442622_

**Comment by jnikula** [comment]
https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1773905066

> Wold you accept PR with below patch?
> 
> ```diff
> --- a/doc/conf.py
> +++ b/doc/conf.py
> @@ -5,6 +5,7 @@
> 
>  import os
>  import sys
> +sys.path.insert(0, os.path.abspath('../src'))
> 
>  # -- Project information -----------------------------------------------------
>  # https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
> ```
> 
> It allows build documention out of only source tree without have `hawkmoth` installed.

The reason we don't have this in docs or tests is to ensure they all work with the *installed* package. Building the docs is also part of testing in the sense that they dogfood the package in a normal Sphinx setting instead of in a pytest suite.

Some time ago I managed to do a release where all tests passed, but you couldn't actually use the package. Quite embarrassing. That's when I added the `src/` subdir (which seems to be the recommended approach) and started using editable installs for testing. I'd rather not repeat that experience! :)

With that in mind, can you think of other alternatives to handle this?

**Comment by jnikula** [comment]
https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1773920679

> The reason we don't have this in docs or tests is to ensure they all work with the _installed_ package

- Packaging usually is done from non-root account
- Installed version  may be different that this one in source tree

**Comment by jnikula** [comment]
https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1773926088

With installed I meant an editable install in a virtual environment, for development. But I don't claim to be anywhere close to a Python packaging expert. I'll need to revisit this part.

In the mean time, 0.16.0 is out, hopefully with the other issues fixed.

**Comment by jnikula** [comment]
https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1773932796

Nothing in the conf.py requires editable module.
That requirement is purely artificial which proves that one line patch.

**Comment by jnikula** [comment]
https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1773933907

And yet another note about that one line modification.
That fix bases on what is i sphinx example copy.py https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

**Comment by jnikula** [comment]
> [#197 (comment)](https://github.com/jnikula/hawkmoth/issues/197#issuecomment-1773932796) by @kloczek
> 
> Nothing in the conf.py requires editable module. That requirement is purely artificial which proves that one line patch.

Superficially this is all true. I tried to explain the rationale for it.

Imagine a situation where `src/` does not match what actually gets packaged. With `src/` in Python path, the documentation build might succeed locally and in github CI, but fail with packaged hawkmoth. This is exactly what happened with v0.13.0 and the whole release was bust, see 9ad923e5cf0f ("build: actually package hawkmoth.ext.*").

For hawkmoth, the documentation build tests the real world usage of the extension. It's not "just" documentation. Unconditionally adding `src/` to Python path makes it unnecessarily hard to test the documentation build against _the package built from_ `src/`.

Please see

- https://hynek.me/articles/testing-packaging/
- https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
- https://docs.pytest.org/en/latest/explanation/goodpractices.html

They all tell you to avoid using the source directly.

---

Maybe the key word here is _unconditionally_. Maybe we can find a way to test the packaged version of hawkmoth **and** let folks build the documentation using the extension directly from `src/`.

**Comment by jnikula** [comment]
Cc: @BrunoMSantos

**Comment by jnikula** [comment]
@kloczek hopefully fixed, please reopen if you're still hitting issues with this!

**Comment by kloczek** [comment]
Thank you very much 👍 😄
