### ISSUE TITLE
Support multiple versions of <insert dependency>

### ISSUE THREAD

**Issue by BrunoMSantos** [jnikula/hawkmoth#24]
I think it's fair to say that further development is blocked on Sphinx 2 vs 3 support. There has been some light discussion about this already and it's not the 1st time it arises. This issue is to see if there is consensus on what to do about it. And if we go down this route, probably we shouldn't focus this on the different Sphinx versions only.

This is what I can think of, admittedly far from a solution:

* For ease of maintenance, the makefiles should probably handle `pip` to install and clean local environments for testing all the different packages. This is not a good answer for testing different Clang versions though. For Clang, is there an easy OS/distro-agnostic alternative? Maybe we should stick to the versions used by maintainers and deal with bug reports as they appear.

* Supporting multiple code paths in the parser will be messy in its current form and ideally shouldn't happen before we further modularize it, but I wouldn't want to work on that until after this to avoid ad hoc solutions to testing. So maybe it's easier to let the parser get more complicated initially and address that afterwards? The upside is that I don't think the fallout will be too big at this moment.

* How to manage sets of test inputs/outputs?

* What should we do about the documentation? Note that older directives syntax will not work on newer Sphinx and vice versa, so presenting the compiled results from both is not trivial, but we could at least present the different `rst` outputs.

-----
Note: just to mention an (the?) alternative, we can simply follow upstream. And note this could be a temporary decision to help clean the backlog a bit without this thing holding everything down. Will we have the heart to go back afterwards though? :see_no_evil:

**Comment by jnikula** [comment]
I haven't made up my mind, but I'm starting to lean towards ditching Sphinx 2 support and going Sphinx 3 all the way. First, the Sphinx upstream has shown over the years that they will keep breaking compatibility, and similar issues will keep cropping up. Hawkmoth is still a tiny project with few developers, and taking on supporting multiple Sphinx version is, I think, against one of the main goals of the project - implementation simplicity - and quite frankly unsustainable. Second, anyone using Hawkmoth is already using bleeding edge software through PIP. Is it that much of a deal to require latest release of Sphinx?

I think Clang probably provides better compatibility across versions, and as such is likely not as big of a problem as Sphinx. Also, Clang is more likely to be installed through the distro package manager, and the user might not have as easy an option to use a very recent version of it. IOW, I think it's more important to support older versions of Clang, but I also presume it's not as problematic as Sphinx. I would try to ensure the output is the same regardless of Clang versions, making testing easier.

For testing different Clang versions, I think it might be useful to set up Docker images to automate. But for day-to-day (eh, month-to-month at the current pace) development what the developers happen to have is probably good enough.

Thoughts?

**Comment by BrunoMSantos** [comment]
Well, I don't think it will come as a surprise, but yeah, I'm always happy to drop support for old stuff given the opportunity, and having no user base to speak of sounds to me like a really nice opportunity.

+1

**Comment by jnikula** [comment]
Should be fixed by pull #26 - go with sphinx 3.

**Comment by jnikula** [comment]
I think for Sphinx the verdict is to support whatever is trivial to support, but anything bigger like the C Domain changes from Sphinx 2 to 3 we'll break compatibility. I don't think there is much point in supporting old versions of Sphinx in Hawkmoth at this time.

We can add tests for different versions of clang as issues arise, however the backward compatibility in clang seems to be pretty good.

I don't think there's need to keep this issue around, closing.
