### ISSUE TITLE
cautodoc_clang problem when mixing -D and -I

### ISSUE THREAD

**Issue by LudovicGuerra** [jnikula/hawkmoth#28]
In my conf.py file, I define the cautodoc clang to this value:
`cautodoc_clang ="-I../include,-I" + os.path.abspath(os.path.join(os.getenv('CCES'), "Blackfin", "include"))`

Which work fine

If I do:
`cautodoc_clang = "-D__ADSPBLACKFIN__,-D_ADI_COMPILER"`

I don't have any error also

Also 

`cautodoc_clang = "-D__ADSPBLACKFIN__,-D_ADI_COMPILER," + "-I../include"`

is working fine

But If i do
`
cautodoc_clang = "-D__ADSPBLACKFIN__,-D_ADI_COMPILER," + "-I../include,-I" + os.path.abspath(os.path.join(os.getenv('CCES'), "Blackfin", "include"))`

I have the following error:

> Exception occurred:
>   File "c:\users\ludovic.guerra\appdata\local\programs\python\python38-32\lib\site-packages\hawkmoth\parser.py", line 281, in clang_di
> agnostics
>     errors.extend([(sev[diag.severity], diag.location.file.name,
> AttributeError: 'NoneType' object has no attribute 'name'
> The full traceback has been saved in C:\cygwin64\tmp\sphinx-err-qlwjvd43.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> make: *** [Makefile:23: html] Error 2
>

**Comment by jnikula** [comment]
Thanks for the report. There's a fix to the error you're seeing in the `clang-diagnostics-fix` branch: https://github.com/jnikula/hawkmoth/tree/clang-diagnostics-fix

However, I think you're hitting some *other* error, possibly incorrect arguments to clang, and we're hitting an error in printing the diagnostics for that other error...

N.b. you may need to add `SPHINXOPTS=-v` to actually see all diagnostics.

**Comment by LudovicGuerra** [comment]
The error have been solved in the branch clang-diagnostics-fix. It is possible to have an official version with those fixes ?

**Comment by jnikula** [comment]
Thanks for testing. I'll give @BrunoMSantos a little bit of time to chime in on the changes, but you can expect a release by the end of the week.

**Comment by BrunoMSantos** [comment]
Hi guys. It looks good to me, feel free to push the changes.

On a side note, I'm not sure how I could have reviewed this in github if I had any comments. I couldn't figure out how to leave comments on the actual commits. I must be loosing touch xD

**Comment by jnikula** [comment]
@LudovicGuerra v0.7.0 release with the fixes is now in pypi.
