### ISSUE TITLE
Include files not found

### ISSUE THREAD

**Issue by LudovicGuerra** [jnikula/hawkmoth#29]
Clang doesn't find some include file (which is normal), and show an error like this:

> C:\Users\*\Desktop\Code\f1\ula\doc\drivers\control\RTC\drv_rtc_pcf85063_api.rst:24: WARNING: ../include\sys/type.h:21: 'inttypes.h' file not found

If I give clang the folder where inttypes.h is, I will have a cascade of error (redefinition, etc)
I searched through  clang parameters (https://releases.llvm.org/6.0.0/tools/clang/docs/ClangCommandLineReference.html) but I didn't find any to ignore specific includes.

Do you have any idea how I could handle this problem ?

**Comment by jnikula** [comment]
Is it really supposed to be `sys/type.h` and not `sys/types.h`?

Have you tried `clang` on the file directly, without Sphinx or Hawkmoth?

**Comment by LudovicGuerra** [comment]
Yes as sys/type.h is our own file.
No I didn't tried clang directly, as I expect it to have the same error. I used the parameters -I to give our include files. But when clang read the files, It search some include file (as inttypes.h) which are located somewhere else in the system, but if I add them I have too many error in cascade as no macro are defined for example. I'd like to simply says: "Please ignore inttypes.h include and don't try to parse it"

**Comment by jnikula** [comment]
I'm at a point where I'm just guessing...

I'd think clang should be able to find its own standard includes. That smells like a clang installation problem to me. On the other hand, when you're adding include paths with `-I`, are you pointing them at clang standard includes or something else? It's quite possible e.g. visual studio standard includes won't work.

**Comment by wkschwartz** [comment]
I was having similar problems on macOS:

```
<omitted>.rst:13: WARNING: <omitted>.h:6: 'stddef.h' file not found
```

Appending `-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include` to `cautodoc_clang` in `conf.py` got rid the errors except for missing `stdarg.h`, which doesn't appear to be in that directory.

```console
$ python --version
Python 3.7.10
$ pip list | grep clang
libclang                      11.1.0
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jnikula** [comment]
Turns out `libclang` does not infer the system include directories the way `clang` on the command line does.

I'm considering adding some code to query the information from `clang`. Would you mind running this on macOS (@wkschwartz) and Windows (@LudovicGuerra), and seeing if it works at all and produces sensible results? Just copy-paste it to a file, and run `python3 file.py` or `python3 file.py /path/to/clang`.

For me, it prints `['-I/usr/local/include', '-I/usr/lib/llvm-7/lib/clang/7.0.1/include', '-I/usr/include/x86_64-linux-gnu', '-I/usr/include']`, which could then be passed to `libclang`.

```
# Copyright (c) 2021 Jani Nikula <jani@nikula.org>
# Licensed under the terms of BSD 2-Clause, see LICENSE for details.

import subprocess

def _get_include_paths(clang_path):
    result = subprocess.run([clang_path, '-E', '-Wp,-v', '-'],
                            stdin=subprocess.DEVNULL,
                            capture_output=True,
                            check=True,
                            text=True)

    output = [s.strip() for s in result.stderr.splitlines()]

    start = output.index('#include <...> search starts here:')
    stop = output.index('End of search list.')

    output = output[start+1:stop]

    return output

def get_include_args(clang_path):
    try:
        include_paths = _get_include_paths(clang_path)
    except RuntimeError as e:
        return None

    if len(include_paths) == 0:
        return None

    return ['-I' + path for path in include_paths]

if __name__ == '__main__':
    import sys
    print(get_include_args(sys.argv[1] if len(sys.argv) > 1 else 'clang'))

```

**Comment by wkschwartz** [comment]
I replaced `print` with [`pprint`](https://docs.python.org/3/library/pprint.html#pprint.PrettyPrinter.pprint) and got the following output
```python
['-I/usr/local/include',
 '-I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include',
 '-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include',
 '-I/Library/Developer/CommandLineTools/usr/include',
 '-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)']
```
Some notes
1. `/usr/local/include` is where Homebrew installs include files
1. `/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include` appears to contain things like intrinsics, cuda, opemmp, etc.
1. `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include`, as discussed, contains most of the standard headers
1. `/Library/Developer/CommandLineTools/usr/include` contains the C++ standard library headers and some Swift headers ("SwiftRemoteMirror", not sure what that is)
1. `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks` is a directory (so the trailing space + `(framework directory)` is a parsing error) containing all the various Apple APIs, e.g., Carbon, Cocoa, Foundation, etc

**Comment by jnikula** [comment]
Thanks for testing. Apparently `(framework directory)` is part of the output of `echo | clang -E -Wp,-v -` on macOS?

**Comment by wkschwartz** [comment]
```console
$ echo | clang -E -Wp,-v -
clang -cc1 version 12.0.0 (clang-1200.0.32.29) default target x86_64-apple-darwin19.6.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 366 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2

```

Lines starting with `#`, plus the final extra newline, are written to stdout. Everything else is written to stderr.

**Comment by wkschwartz** [comment]
Finally found `stdarg.h`: it's in `/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include`
