### ISSUE TITLE
Incorrect bracket placement for array parameters

### ISSUE THREAD

**Issue by wkschwartz** [jnikula/hawkmoth#36]
This is very similar to #17. A function parameter `array` of type `T*` may declared `T array[]` (which I like to do to clarify that the parameter is an array rather than an out parameter (cf. #32)). The following input

```c
/** Test */
_Bool set_thing_array(struct thing* self, size_t len, const double array[]);
```
produces this warning
```
/path/to/test.h:14: WARNING: Error in declarator or parameters
Invalid C declaration: Expecting "," or ")" in parameters, got "a". [error at 71]
  _Bool set_thing_array(struct thing * self, size_t len, const double [] array)
  -----------------------------------------------------------------------^
```
and this incorrect output
<img width="659" alt="set_thing_array" src="https://user-images.githubusercontent.com/1417749/113593661-46f9b800-95fc-11eb-921f-d185bd33a6b3.png">
Clearly the function prototype isn't being fully parsed.

**Comment by jnikula** [comment]
Thanks for the report. I've got a fix locally, indeed just doing the same as the fix for #17 does also for function parameters.
