### ISSUE TITLE
Incorrect parenthesis placement for function-pointer struct members

### ISSUE THREAD

**Issue by wkschwartz** [jnikula/hawkmoth#37]
This is similar to #17 and #36.
Input:
```c
/** Test */
struct test {
	/** Return a static, null-terminated string. */
	const char* (*const get_name)(void);
};
```
(That is, a struct named `test` containing an immutable field named `get_name`, which is a pointer to a function taking no arguments and returning a pointer an immutable array of `char`s.)

Warning during build:
```
/path/to/test.h:117: WARNING: Error in declarator
If declarator-id with parameters:
  Invalid C declaration: Expected identifier in nested name. [error at 12]
    const char *(*const)(void) get_name
    ------------^
If parenthesis in noptr-declarator:
  Error in declarator or parameters
  Invalid C declaration: Expected identifier in nested name. [error at 19]
    const char *(*const)(void) get_name
    -------------------^
```
Rendering:
<img width="379" alt="get_name" src="https://user-images.githubusercontent.com/1417749/113597497-6b0bc800-9601-11eb-80bd-30d25da97541.png">
And then
```rst
:c:member:`test.get_name`
```
cross references don't work.

**Comment by jnikula** [comment]
Thanks for the report. This is actually the same as #21, just with additional qualifiers (const) that throw off the fix.
