### ISSUE TITLE
Bump Python requirement to v3.6+ for f-strings?

### ISSUE THREAD

**Issue by jnikula** [jnikula/hawkmoth#40]
We use quite a bit of `str.format()` in the codebase that would benefit from converting to [f-strings]( https://docs.python.org/3/reference/lexical_analysis.html#f-strings), both for brevity and clarity. However, f-strings were introduced in Python 3.6. Are there any real drawbacks to bumping the Python requirement from 3.4 to 3.6?

**Comment by BrunoMSantos** [comment]
Yes please! :+1:

**Comment by wkschwartz** [comment]
3.4 and and 3.5 are no longer maintained. 3.6 reaches its end of life in December: https://www.python.org/downloads/ and https://www.python.org/dev/peps/pep-0494/#lifespan

**Comment by jnikula** [comment]
Thanks for the info!

**Comment by sembooooo** [comment]
Hi people, 
i am very new to this hawkmoth github. 
```3.4 and and 3.5 are no longer maintained. 3.6 reaches its end of life in December:```
 Does it mean that backward compatibility need not be given ?

**Comment by jnikula** [comment]
> `3.4 and and 3.5 are no longer maintained. 3.6 reaches its end of life in December:`
> Does it mean that backward compatibility need not be given ?

We could set the requirement as we see fit, and people just couldn't use Hawkmoth on older versions of Python. But since 3.4 and 3.5 are no longer maintained, people should really upgrade their Python anyway.

**Comment by sembooooo** [comment]
>  But since 3.4 and 3.5 are no longer maintained, people should really upgrade their Python anyway.

makes sense.

**Comment by sembooooo** [comment]
hi jnikula,
I am planning to write test specification(using sphinx-needs) in the .c file and then link the requirements to the test case and generate sphinx html file . Is this possible with Hawkmoth

**Comment by jnikula** [comment]
> I am planning to write test specification(using sphinx-needs) in the .c file and then link the requirements to the test case and generate sphinx html file . Is this possible with Hawkmoth

Never used that, but seems to me you can just use the relevant rst directives in the documentation comments.

PS. Please file new issues for new questions instead of adding to old ones. Thanks. :)
