### ISSUE TITLE
AutodocReporter no longer included in sphinx v2.0

### ISSUE THREAD

**Issue by Livingwind** [jnikula/hawkmoth#6]
Since sphinx v2.0 AutodocReporter has been removed from the autodoc module causing an exception on sphinx v2.0+.

The offending line: https://github.com/jnikula/hawkmoth/blob/81424935ede79fd8836b8b18f6ad6210fd3c0d38/hawkmoth/__init__.py#L20

I've been able to remove this line locally without causing any issues but this requires further verification.

**Comment by BrunoMSantos** [comment]
Hm, this was known to be deprecated and was supposedly fixed in commit 1252995a872f2cf115ff26a58a576682514e16f9.

I guess I forgot to remove that line :/

Thanks for reporting.

**Comment by Livingwind** [comment]
No problem, thanks for providing such a useful extension!

**Comment by jnikula** [comment]
Thanks for the report, and the fix.
