### ISSUE TITLE
Continuation lines in parameter descriptions are broken

### ISSUE THREAD

**Issue by bastibe** [jnikula/hawkmoth#64]
I have a long parameter description that looks like this:

```
  :param param1: an initialized variable
  :param param2: A structure containing various feature data, as configured in
                  SomeFunction and supported by the input data
```

The second parameter description is broken into two lines. This generates a warning "WARNING: Field list ends without a blank line; unexpected unindent." and renders as if I had written

```
  :param param1: an initialized variable
  :param param2: A structure containing various feature data, as configured in

  SomeFunction and supported by the input data
```

Is there a workaround for this, maybe some way of marking the param2-line as continuing on the next line? I know that the above documentation works fine in Python.

**Comment by jnikula** [comment]
Thanks for the report. I can't reproduce this; can you come up with a minimal C documentation comment that reproduces the problem for you?

**Comment by jnikula** [comment]
Okay, I can come up with this:

```
/**
 * :param p: foo
 *	bar
 */
```

with a single TAB character as indent:

```
/**
 * :param p: foo
 *<TAB>bar
 */
```

Any two or more whitespace characters instead of a single TAB works for me.

**Comment by bastibe** [comment]
Sorry for the too-small example, and thank you for answering so quickly. 

It seems that the problem is a lack of asterisks at the beginning of the line:

```
/**
 *  :param p: this
 *    works correctly
 */

/**
  :param p: this
    does not
 */
```

**Comment by jnikula** [comment]
The asterisks weren't meant to be required, but seems like not having it indeed removes all indentation whitespace. Clearly a bug.

**Comment by bastibe** [comment]
Thank you!

**Comment by jnikula** [comment]
Thanks for the report!
