### ISSUE TITLE
Option to include autodoc output in toctree

### ISSUE THREAD

**Issue by Rjvs** [jnikula/hawkmoth#83]
Output of autodoc currently does not populate the toctree, which might often be desirable but in our case it would be nice to be able to jump to references quickly without adding the maintenance overhead of manually referring to each struct/etc in ReST.

**Comment by jnikula** [comment]
I think this is more of a Sphinx issue, as Hawkmoth basically just adds the [C domain directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#the-c-domain) and Sphinx should handle the rest. That said, I'll leave this open for now and add any ideas I might have on this.

The C elements do get added to the general index (:ref:\`genindex\`), but I guess that's not what you're after.

**Comment by Rjvs** [comment]
Ah, okay, so if https://github.com/sphinx-doc/sphinx/issues/6316 is ever resolved, that should take care of this issue, then.

**Comment by jnikula** [comment]
> Ah, okay, so if [sphinx-doc/sphinx#6316](https://github.com/sphinx-doc/sphinx/issues/6316) is ever resolved, that should take care of this issue, then.

That one has been resolved... but apparently only for the py domain it. See https://github.com/sphinx-doc/sphinx/issues/6316#issuecomment-1284942866

No matter what this should be resolved in Sphinx itself. Closing. I suggest following up on the Sphinx issue.
